import React from 'react';
import "./Resource.css"
const Resource = () => {
    return (
        <div className="single-resource">
            <div className="single-resource-in">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque in eius id veniam, cupiditate accusantium optio dolorem explicabo accusamus ad facere nemo ullam quos. Voluptatum explicabo suscipit dolorum voluptates nulla.</p>
                <small>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eum pariatur cumque facere expedita similique dicta recusandae vero nesciunt voluptas voluptate dolorem amet nemo, et earum impedit ratione ut dolor libero nihil harum eaque. Saepe repellat deleniti atque incidunt dolorem voluptatem recusandae consequuntur deserunt mollitia labore, magni laborum laudantium quo ipsa numquam reprehenderit quos cupiditate excepturi ipsum itaque illo id minus alias. Quaerat cumque assumenda atque vero, iste laudantium omnis hic repudiandae accusantium ratione autem harum dolorum debitis asperiores eius! Officiis, dolore. Pariatur adipisci ab veritatis, doloremque veniam est mollitia nobis, tenetur explicabo dolorum illum a non reiciendis cumque dolore. Cum quos inventore, suscipit explicabo doloribus, minima ratione optio architecto maiores nesciunt est cupiditate odit eveniet accusantium molestias consequuntur nihil maxime. At ad dolores mollitia veniam, culpa maxime rerum. At provident dignissimos voluptatum voluptates blanditiis possimus animi voluptatem, minus eius, sit libero placeat, explicabo ab. Accusamus maiores magni reiciendis ipsam nihil architecto omnis tempore! Beatae illum debitis voluptatibus amet minus, enim quibusdam minima aut, nulla facere dolorum sint deserunt necessitatibus dolores, obcaecati unde officia fuga quis eveniet ipsa quam. Non molestiae neque maxime suscipit, voluptatibus voluptas atque doloribus, ex, temporibus cumque expedita est qui dolores deleniti! Deleniti, consectetur! Maiores optio nemo maxime ad dolorum, earum voluptatem molestias mollitia. Quod, modi dolores dolorem nisi nulla amet dolorum explicabo excepturi maxime fuga alias iusto et eveniet. Labore temporibus dolorum debitis ducimus consectetur explicabo, corrupti a dolore ullam sint repudiandae quod itaque alias officiis laudantium quaerat esse similique iusto aperiam fuga. Similique cumque suscipit tempore ducimus sit reprehenderit maxime laudantium dolores eius voluptates reiciendis molestias quaerat quod placeat, possimus dolorem asperiores veniam distinctio doloribus! Distinctio esse eaque molestiae sint voluptatum perferendis cum, ab magni odio sapiente voluptatem culpa minima impedit consectetur tenetur fugiat quaerat voluptatibus veritatis ea dicta eum. Modi nemo nihil accusamus tempore?</small>
                <small>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eum pariatur cumque facere expedita similique dicta recusandae vero nesciunt voluptas voluptate dolorem amet nemo, et earum impedit ratione ut dolor libero nihil harum eaque. Saepe repellat deleniti atque incidunt dolorem voluptatem recusandae consequuntur deserunt mollitia labore, magni laborum laudantium quo ipsa numquam reprehenderit quos cupiditate excepturi ipsum itaque illo id minus alias. Quaerat cumque assumenda atque vero, iste laudantium omnis hic repudiandae accusantium ratione autem harum dolorum debitis asperiores eius! Officiis, dolore. Pariatur adipisci ab veritatis, doloremque veniam est mollitia nobis, tenetur explicabo dolorum illum a non reiciendis cumque dolore. Cum quos inventore, suscipit explicabo doloribus, minima ratione optio architecto maiores nesciunt est cupiditate odit eveniet accusantium molestias consequuntur nihil maxime. At ad dolores mollitia veniam, culpa maxime rerum. At provident dignissimos voluptatum voluptates blanditiis possimus animi voluptatem, minus eius, sit libero placeat, explicabo ab. Accusamus maiores magni reiciendis ipsam nihil architecto omnis tempore! Beatae illum debitis voluptatibus amet minus, enim quibusdam minima aut, nulla facere dolorum sint deserunt necessitatibus dolores, obcaecati unde officia fuga quis eveniet ipsa quam. Non molestiae neque maxime suscipit, voluptatibus voluptas atque doloribus, ex, temporibus cumque expedita est qui dolores deleniti! Deleniti, consectetur! Maiores optio nemo maxime ad dolorum, earum voluptatem molestias mollitia. Quod, modi dolores dolorem nisi nulla amet dolorum explicabo excepturi maxime fuga alias iusto et eveniet. Labore temporibus dolorum debitis ducimus consectetur explicabo, corrupti a dolore ullam sint repudiandae quod itaque alias officiis laudantium quaerat esse similique iusto aperiam fuga. Similique cumque suscipit tempore ducimus sit reprehenderit maxime laudantium dolores eius voluptates reiciendis molestias quaerat quod placeat, possimus dolorem asperiores veniam distinctio doloribus! Distinctio esse eaque molestiae sint voluptatum perferendis cum, ab magni odio sapiente voluptatem culpa minima impedit consectetur tenetur fugiat quaerat voluptatibus veritatis ea dicta eum. Modi nemo nihil accusamus tempore?</small>
            </div>
        </div>
    );
};

export default Resource;